# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Fetch blog posts from BrightBotBlog.com
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  schedule:
    - cron: "* */4 * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install node dependencies
      run: yarn
    - name: Run node script
      run: yarn build
    - name: Git setup
      run: git config --global user.email github-bot@example.com && git config --global user.name github-bot
    - name: Git commit README.md file
      run: git diff --quiet && git diff --staged --quiet || git commit -am '[BOT] Update readme' && git push
